----
- name: Create Renovate Cron Job to start Docker Container
  ansible.builtin.cron:
    name: "renovate docker"
    minute: "0"
    hour: "0"
    job: "docker run --rm \
     -e RENOVATE_PLATFORM={{ renovate_platform }} \
     -e RENOVATE_ENDPOINT={{ renovate_endpoint }} \
     -e RENOVATE_GIT_FS={{ renovate_git_fs }} \
     -e RENOVATE_USERNAME={{ renovate_username }} \
     -e RENOVATE_PASSWORD={{ renovate_password }} \
     -e RENOVATE_AUTODISCOVER={{ renovate_autodiscover }} \
     -e RENOVATE_COMMIT_MESSAGE=\"{{ renovate_ticket_number }} {{ '{{' }}commitMessagePrefix{{ '}}' }} {{ '{{' }}commitMessageAction{{ '}}' }} {{ '{{' }}commitMessageTopic{{ '}}' }} {{ '{{' }}commitMessageExtra{{ '}}' }} {{ '{{' }}commitMessageSuffix{{ '}}' }}\" \
     -e RENOVATE_ONBOARDING_COMMIT_MESSAGE=\"{{ renovate_ticket_number }} Add renovate.json\" \
     -e RENOVATE_BRANCH_PREFIX=\"{{ renovate_branch_prefix }}\" \
     -e RENOVATE_ONBOARDING_BRANCH=\"{{ renovate_onboarding_branch }}\" \
     -e RENOVATE_AUTOMERGE=\"{{ renovate_automerge }}\" renovate/renovate:29.18.1"